---
- name: Ensuring subscription-manager is installed
  yum:
    name: subscription-manager
    state: latest

- name: Disabling all repositories
  command: subscription-manager repos --disable="*"

- name: Enabling only the required repositories
  command: subscription-manager repos --enable="{{ item }}"
  with_items: "{{ repos_to_enable }}"

- name: Installing Docker
  yum:
    name: docker-{{ docker_version }}
    state: present

- name: Copying Docker storage setup file
  template:
    src: "templates/docker-storage-setup.j2"
    dest: "/etc/sysconfig/docker-storage-setup"

- name: Configuring docker storage
  command: docker-storage-setup
  ignore_errors: true
  register: docker_storage

- name: Warning operator if Docker storage failed to install
  debug:
    msg: "WARNING: Docker storage could not be configured - Using default option, which has reduced performance!"
  when: docker_storage.rc != 0

- name: Starting the Docker service
  service:
    name: docker
    enabled: yes
    state: started

- name: Checking if pip is installed
  yum:
    name: python-pip
    state: present
    disable_gpg_check: yes

- name: Checking if Docker-Py is installed
  pip:
    name: docker-py

- name: Checking Which is installed
  yum:
    name: "which"
    state: "present"

- name: Checking if Docker Compose is installed
  command: which docker-compose
  failed_when: false
  changed_when: false
  register: result

- name: Installing Docker Compose if not present
  get_url:
    url: "https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-{{ ansible_system }}-{{ ansible_architecture }}"
    dest: "/usr/local/bin/docker-compose"
    mode: "0644"
  when: result.rc != 0
...
